name: Design - Publish - $(Date:yyyy.MM.dd).$(BuildID) 

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    exclude:
      - README.md
      - .github/**
      - tests/**
pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: krosoft-dev/Krosoft.DevOps.AzureDevOps
      endpoint: github.com_krosoft-dev
      ref: refs/heads/main

parameters:
  - name: environments
    displayName: "Environnements à déployer"
    type: object
    default:
      - Production

variables:
  - template: vars/vars_node.yml@templates
  - template: vars/vars.yml@templates
  - template: vars/vars.yml

extends:
  template: templates/pipelines/node/docker-deploy-template.yml@templates
  parameters:
    pool: ${{ variables.poolName }}
    sshEndpointPrefix: ${{ variables.sshEndpointPrefix }}
    envVariablesFilePrefix: ${{ variables.envVariablesFilePrefix }}
    environments: ${{ parameters.environments }}
    targetFolder: ${{ variables.targetFolder }}
    imageName: ${{ variables.imageName }}
    nodeVersion: ${{ variables.nodeVersion }}
    buildScript: "storybook:build"
    passViteArgs: false
    outputDir: "storybook-static"
